# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  node:
    docker:
      - image: node:8.16.0-jessie
jobs:
  checkout:
    executor: node
    steps:
      - checkout:
          path: ~/repo
      - persist_to_workspace:
          root: ~/
          paths: 
            - repo
            - .ssh/known_hosts
  build:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/repo && yarn && yarn build && rm -rf docs && mv build docs
      - persist_to_workspace:
          root: ~/
          paths: 
            - repo
  update:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys:
          fingerprints:
            - "82:60:82:2b:af:d1:1e:6a:68:8e:e3:13:67:36:2a:d8"
      - run: git config --global user.email "dan@3vl.ca" && git config --global user.name "Dan Imbrogno"
      - run: "cd ~/repo && git add -A && git commit --message=\"chore(release): update docs folder [skip ci]\" && git push origin master"
workflows:
  version: 2
  publish:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - update:
          requires:
            - build