# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  node:
    docker:
      - image: node:8.16.0-jessie
  base:
    machine:
      image: circleci/classic:201808-01
jobs:
  checkout:
    executor: node
    steps:
      - checkout:
          path: ~/repo
      - persist_to_workspace:
          root: ~/
          paths: 
            - repo
  build:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/repo && yarn build
      - persist_to_workspace:
          root: ~/
          paths: 
            - repo
  update:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run: git config --global user.email "dan@3vl.ca" && git config --global user.name "Dan Imbrogno"
      - run: "cd ~/repo && git add build/\\* && git commit --message=\"chore(release): update build folder [skip ci]\""
workflows:
  version: 2
  publish:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - update:
          requires:
            - build